In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score
import joblib
import pandas as pd
import numpy as np
from imblearn.over_sampling import SMOTE


In [2]:
df = pd.read_csv(r"C:\SASTRA\shanthi mam project\aif_emo_sen_new.csv")
print(df.head())

      author                    poem_name  TOTAL_WORD_COUNT  \
0  avvaiyaar           அமுதும்‌ அன்பும்‌!                15   
1  avvaiyaar                     அழகு எது                18   
2  avvaiyaar                       ஆரையடா                15   
3  avvaiyaar                  இடம்‌ எங்கே                15   
4  avvaiyaar  இன்றுபோல்‌ என்றும்‌ இரும்‌!                15   

   UNIQUE_WORD_COUNT  TYPE_TOKEN_RATIO  AVG_WORD_LENGTH  STD_WORD_LENGTH  \
0                 15          1.000000         7.600000         2.184796   
1                 16          0.888889         6.166667         2.967416   
2                 15          1.000000         7.000000         2.129163   
3                 15          1.000000         7.733333         2.694851   
4                 15          1.000000         7.800000         2.343786   

   HAPAX_LEGOMENA  FUNCTION_WORD_FREQ  STOP_WORD_RATIO  ...  TOTAL_LINES  \
0              15                   0              0.0  ...            4   
1           

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   author                  160 non-null    object 
 1   poem_name               160 non-null    object 
 2   TOTAL_WORD_COUNT        160 non-null    int64  
 3   UNIQUE_WORD_COUNT       160 non-null    int64  
 4   TYPE_TOKEN_RATIO        160 non-null    float64
 5   AVG_WORD_LENGTH         160 non-null    float64
 6   STD_WORD_LENGTH         160 non-null    float64
 7   HAPAX_LEGOMENA          160 non-null    int64  
 8   FUNCTION_WORD_FREQ      160 non-null    int64  
 9   STOP_WORD_RATIO         160 non-null    float64
 10  CHAR_UNIGRAM_ENTROPY    160 non-null    float64
 11  CHAR_BIGRAM_ENTROPY     160 non-null    float64
 12  CHAR_TRIGRAM_ENTROPY    160 non-null    float64
 13  CHAR_DIVERSITY          160 non-null    int64  
 14  RARE_CHAR_RATIO         160 non-null    fl

In [4]:
df = df.drop(columns=["poem_name", "author","Emotion"], axis=1)



In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
from sklearn.inspection import permutation_importance
import joblib
import pickle
import cloudpickle

# Load the dataset
#df = pd.read_csv(r"C:\SASTRA\shanthi mam project\aif_emo_sen_new.csv")
#print(df.info())
#print(df.head())

#Encode the target column
le = LabelEncoder()
y = le.fit_transform(df["Sentiment"])

#Features and target
x = df.drop(columns = ["Sentiment"], axis=1)
print(x.columns)

#Feature scaling
scaler = StandardScaler()
x = scaler.fit_transform(x)


print(x.shape)
print(y.shape)

#Train test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=57)

#Random Forest Classifier
model = RandomForestClassifier(
    n_estimators=1000,
    criterion='gini',
    n_jobs=-1,
    random_state=42,
    max_depth=4
)
model.fit(x_train, y_train)

#Prediction
y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)
f1 = f1_score(y_test, y_test_pred, average='macro')
conf_matrix = confusion_matrix(y_test, y_test_pred)
class_report = classification_report(y_test,y_test_pred, target_names=le.classes_)

print(f"Train Accuracy: {train_acc:.4f}")
print(f"Test Accuracy: {test_acc:.4f}")
print(f"F1-score: {f1:.4f}")
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

"""n_esti = [1000, 2000, 3000, 4000, 5000]
max_depths = [4, 5, 6, 7, 8, 9, 10, 20, 30, None]
crit = ['gini', 'entropy', 'log_loss']
test_size=[0.2,0.23,0.25,0.28,0.3,0.33,0.35,0.38,0.4]

for i in n_esti:
    for j in max_depths:
        for k in crit:
            for l in range(1,101):
                for m in test_size:
                    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=m, random_state=l)
                    model = RandomForestClassifier(
                    n_estimators=i,
                    criterion=k,
                    n_jobs=-1,
                    max_depth=j,
                    random_state=42
                    )
            
                    model.fit(x_train, y_train)
                    y_train_pred = model.predict(x_train)
                    y_test_pred = model.predict(x_test)
                    train_acc = accuracy_score(y_train, y_train_pred)
                    test_acc = accuracy_score(y_test, y_test_pred)
                    print(f"Criterion: {k}, n_estimators: {i}, Max Depth: {j}, Random State: {l}, Test Size: {m}, Test Accuracy: {test_acc:.4f}")"""


Index(['TOTAL_WORD_COUNT', 'UNIQUE_WORD_COUNT', 'TYPE_TOKEN_RATIO',
       'AVG_WORD_LENGTH', 'STD_WORD_LENGTH', 'HAPAX_LEGOMENA',
       'FUNCTION_WORD_FREQ', 'STOP_WORD_RATIO', 'CHAR_UNIGRAM_ENTROPY',
       'CHAR_BIGRAM_ENTROPY', 'CHAR_TRIGRAM_ENTROPY', 'CHAR_DIVERSITY',
       'RARE_CHAR_RATIO', 'AVG_SYLLABLES_PER_WORD', 'AVG_LINE_LENGTH_WORDS',
       'AVG_STANZA_LENGTH', 'TOTAL_LINES', 'ANAPHORA_SCORE', 'EPIPHORA_SCORE',
       'ENJAMBMENT_RATIO', 'ESTIMATED_NOUN_COUNT', 'ESTIMATED_VERB_COUNT',
       'NOUN_VERB_RATIO', 'READABILITY_SCORE'],
      dtype='object')
(160, 24)
(160,)
Train Accuracy: 0.9141
Test Accuracy: 0.8750
F1-score: 0.5873
Confusion Matrix:
 [[ 9  0  2]
 [ 0  0  1]
 [ 1  0 19]]
Classification Report:
               precision    recall  f1-score   support

    Negative       0.90      0.82      0.86        11
     Neutral       0.00      0.00      0.00         1
    Positive       0.86      0.95      0.90        20

    accuracy                           0.88    

C:\Users\kisho\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\kisho\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\kisho\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

'n_esti = [1000, 2000, 3000, 4000, 5000]\nmax_depths = [4, 5, 6, 7, 8, 9, 10, 20, 30, None]\ncrit = [\'gini\', \'entropy\', \'log_loss\']\ntest_size=[0.2,0.23,0.25,0.28,0.3,0.33,0.35,0.38,0.4]\n\nfor i in n_esti:\n    for j in max_depths:\n        for k in crit:\n            for l in range(1,101):\n                for m in test_size:\n                    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=m, random_state=l)\n                    model = RandomForestClassifier(\n                    n_estimators=i,\n                    criterion=k,\n                    n_jobs=-1,\n                    max_depth=j,\n                    random_state=42\n                    )\n\n                    model.fit(x_train, y_train)\n                    y_train_pred = model.predict(x_train)\n                    y_test_pred = model.predict(x_test)\n                    train_acc = accuracy_score(y_train, y_train_pred)\n                    test_acc = accuracy_score(y_test, y_test_pred)\

In [ ]:
import joblib

joblib.dump(model, r'C:\SASTRA\shanthi mam project\new_sentiment\jl\sent_rf_model.joblib')
joblib.dump(scaler, r'C:\SASTRA\shanthi mam project\new_sentiment\jl\sent_rf_scaler.joblib')
joblib.dump(le, r'C:\SASTRA\shanthi mam project\new_sentiment\jl\sent_rf_le.joblib')


with open(r'C:\SASTRA\shanthi mam project\new_sentiment\pic\sent_rf_model.pkl', 'wb') as f:
    pickle.dump(model, f)
with open(r'C:\SASTRA\shanthi mam project\new_sentiment\pic\sent_rf_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
with open(r'C:\SASTRA\shanthi mam project\new_sentiment\pic\sent_rf_le.pkl', 'wb') as f:
    pickle.dump(le, f)


with open(r'C:\SASTRA\shanthi mam project\new_sentiment\clo_pic\sent_rf_model.cpkl', 'wb') as f:
    cloudpickle.dump(model, f)
with open(r'C:\SASTRA\shanthi mam project\new_sentiment\clo_pic\sent_rf_scaler.cpkl', 'wb') as f:
    cloudpickle.dump(scaler, f)
with open(r'C:\SASTRA\shanthi mam project\new_sentiment\clo_pic\sent_rf_le.cpkl', 'wb') as f:
    cloudpickle.dump(le, f)
